### ISSUE TITLE
Omicron alignment issue

### ISSUE THREAD

**Issue by KaimingTao** [hivdb/covid-drdb#16]
Spike NTD position 212 to 215, example: hCoV-19/Germany/HE-FFM-30286807/2021|EPI_ISL_6959871|2021-11-28

**Comment by philiptzou** [comment]
The issue is caused by codon-alignment process done by [hivdb/post-align](https://github.com/hivdb/post-align). In nutshell, position 212 and 214 (not 215!) are too close and the codon-alignment process considers them a single gap but not two.

The solution is a simple alignment profile change, which applies codon alignment to S:1-213 (in nucleotide: 21563-22201) and S:214-1274 (in nucleotide: 22202-25384) separately. This change allows the two gaps won't be merged as a single one. It has been added by hivdb/sierra-sars2@7a768a3.

Attachments:

1. Before the change, the result:
   <img width="1503" alt="Screen Shot 2022-01-16 at 5 40 54 PM" src="https://user-images.githubusercontent.com/809865/149687997-982a8bc8-cea8-4efc-ae50-a2107cf95785.png">
2. After the change, the result:
   <img width="1539" alt="Screen Shot 2022-01-16 at 5 36 29 PM" src="https://user-images.githubusercontent.com/809865/149687714-57f0dcc2-44fe-43f9-a122-9a4e33da0ad5.png">
